// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTM5EihEISELN1j1BeNxfL4htdZfxCWlQ',
    appId: '1:1026014127125:web:296367e7499dff8b53da1c',
    messagingSenderId: '1026014127125',
    projectId: 'totalx-test-1598a',
    authDomain: 'totalx-test-1598a.firebaseapp.com',
    storageBucket: 'totalx-test-1598a.firebasestorage.app',
    measurementId: 'G-G6G080X8VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkYtPkoupD4EVCIj5aU2jkbTAXPXV8_w',
    appId: '1:1026014127125:android:8d79da03c428512853da1c',
    messagingSenderId: '1026014127125',
    projectId: 'totalx-test-1598a',
    storageBucket: 'totalx-test-1598a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdP7WvTcveyOaDY8lFSTkrMa-3v2bU9GY',
    appId: '1:1026014127125:ios:19e4f5574acfb7f253da1c',
    messagingSenderId: '1026014127125',
    projectId: 'totalx-test-1598a',
    storageBucket: 'totalx-test-1598a.firebasestorage.app',
    androidClientId: '1026014127125-qhveq4u21aa7nqq2a3g9sbo0rgulubg2.apps.googleusercontent.com',
    iosClientId: '1026014127125-ae6dnm2cjbtp3kbka8m25sged2mhj7ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalxTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdP7WvTcveyOaDY8lFSTkrMa-3v2bU9GY',
    appId: '1:1026014127125:ios:19e4f5574acfb7f253da1c',
    messagingSenderId: '1026014127125',
    projectId: 'totalx-test-1598a',
    storageBucket: 'totalx-test-1598a.firebasestorage.app',
    androidClientId: '1026014127125-qhveq4u21aa7nqq2a3g9sbo0rgulubg2.apps.googleusercontent.com',
    iosClientId: '1026014127125-ae6dnm2cjbtp3kbka8m25sged2mhj7ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalxTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTM5EihEISELN1j1BeNxfL4htdZfxCWlQ',
    appId: '1:1026014127125:web:519bf92916822cc053da1c',
    messagingSenderId: '1026014127125',
    projectId: 'totalx-test-1598a',
    authDomain: 'totalx-test-1598a.firebaseapp.com',
    storageBucket: 'totalx-test-1598a.firebasestorage.app',
    measurementId: 'G-0QR98RYEX6',
  );
}
